/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogsRouteImport } from './routes/catalogs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HeritageIndexRouteImport } from './routes/heritage/index'
import { Route as HeritageDegBhapkaRouteImport } from './routes/heritage/deg-bhapka'
import { Route as HeritageIngredientsRouteImport } from './routes/heritage/ingredients'
import { Route as HeritageStoryRouteImport } from './routes/heritage/story'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as PoliciesIndexRouteImport } from './routes/policies/index'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies/privacy'
import { Route as PoliciesReturnsRouteImport } from './routes/policies/returns'
import { Route as PoliciesShippingRouteImport } from './routes/policies/shipping'
import { Route as PoliciesTermsRouteImport } from './routes/policies/terms'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as CollectionsCollectionIndexRouteImport } from './routes/collections/$collection/index'
import { Route as ShopCollectionIndexRouteImport } from './routes/shop/$collection/index'
import { Route as ShopCollectionSlugRouteImport } from './routes/shop/$collection/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsRoute = CatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageIndexRoute = HeritageIndexRouteImport.update({
  id: '/heritage/',
  path: '/heritage/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageDegBhapkaRoute = HeritageDegBhapkaRouteImport.update({
  id: '/heritage/deg-bhapka',
  path: '/heritage/deg-bhapka',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageIngredientsRoute = HeritageIngredientsRouteImport.update({
  id: '/heritage/ingredients',
  path: '/heritage/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageStoryRoute = HeritageStoryRouteImport.update({
  id: '/heritage/story',
  path: '/heritage/story',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesReturnsRoute = PoliciesReturnsRouteImport.update({
  id: '/policies/returns',
  path: '/policies/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesShippingRoute = PoliciesShippingRouteImport.update({
  id: '/policies/shipping',
  path: '/policies/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesTermsRoute = PoliciesTermsRouteImport.update({
  id: '/policies/terms',
  path: '/policies/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIndexRoute =
  CollectionsCollectionIndexRouteImport.update({
    id: '/collections/$collection/',
    path: '/collections/$collection/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopCollectionIndexRoute = ShopCollectionIndexRouteImport.update({
  id: '/shop/$collection/',
  path: '/shop/$collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCollectionSlugRoute = ShopCollectionSlugRouteImport.update({
  id: '/shop/$collection/$slug',
  path: '/shop/$collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogs': typeof CatalogsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/heritage/deg-bhapka': typeof HeritageDegBhapkaRoute
  '/heritage/ingredients': typeof HeritageIngredientsRoute
  '/heritage/story': typeof HeritageStoryRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/heritage/': typeof HeritageIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/$collection/$slug': typeof ShopCollectionSlugRoute
  '/collections/$collection/': typeof CollectionsCollectionIndexRoute
  '/shop/$collection/': typeof ShopCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogs': typeof CatalogsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/heritage/deg-bhapka': typeof HeritageDegBhapkaRoute
  '/heritage/ingredients': typeof HeritageIngredientsRoute
  '/heritage/story': typeof HeritageStoryRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/heritage': typeof HeritageIndexRoute
  '/journal': typeof JournalIndexRoute
  '/policies': typeof PoliciesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/shop/$collection/$slug': typeof ShopCollectionSlugRoute
  '/collections/$collection': typeof CollectionsCollectionIndexRoute
  '/shop/$collection': typeof ShopCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogs': typeof CatalogsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/heritage/deg-bhapka': typeof HeritageDegBhapkaRoute
  '/heritage/ingredients': typeof HeritageIngredientsRoute
  '/heritage/story': typeof HeritageStoryRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/returns': typeof PoliciesReturnsRoute
  '/policies/shipping': typeof PoliciesShippingRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/heritage/': typeof HeritageIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/$collection/$slug': typeof ShopCollectionSlugRoute
  '/collections/$collection/': typeof CollectionsCollectionIndexRoute
  '/shop/$collection/': typeof ShopCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogs'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/heritage/deg-bhapka'
    | '/heritage/ingredients'
    | '/heritage/story'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/shipping'
    | '/policies/terms'
    | '/heritage/'
    | '/journal/'
    | '/policies/'
    | '/shop/'
    | '/shop/$collection/$slug'
    | '/collections/$collection/'
    | '/shop/$collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogs'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/heritage/deg-bhapka'
    | '/heritage/ingredients'
    | '/heritage/story'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/shipping'
    | '/policies/terms'
    | '/heritage'
    | '/journal'
    | '/policies'
    | '/shop'
    | '/shop/$collection/$slug'
    | '/collections/$collection'
    | '/shop/$collection'
  id:
    | '__root__'
    | '/'
    | '/catalogs'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/heritage/deg-bhapka'
    | '/heritage/ingredients'
    | '/heritage/story'
    | '/policies/privacy'
    | '/policies/returns'
    | '/policies/shipping'
    | '/policies/terms'
    | '/heritage/'
    | '/journal/'
    | '/policies/'
    | '/shop/'
    | '/shop/$collection/$slug'
    | '/collections/$collection/'
    | '/shop/$collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogsRoute: typeof CatalogsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HeritageDegBhapkaRoute: typeof HeritageDegBhapkaRoute
  HeritageIngredientsRoute: typeof HeritageIngredientsRoute
  HeritageStoryRoute: typeof HeritageStoryRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesReturnsRoute: typeof PoliciesReturnsRoute
  PoliciesShippingRoute: typeof PoliciesShippingRoute
  PoliciesTermsRoute: typeof PoliciesTermsRoute
  HeritageIndexRoute: typeof HeritageIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionSlugRoute: typeof ShopCollectionSlugRoute
  CollectionsCollectionIndexRoute: typeof CollectionsCollectionIndexRoute
  ShopCollectionIndexRoute: typeof ShopCollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs': {
      id: '/catalogs'
      path: '/catalogs'
      fullPath: '/catalogs'
      preLoaderRoute: typeof CatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage/': {
      id: '/heritage/'
      path: '/heritage'
      fullPath: '/heritage/'
      preLoaderRoute: typeof HeritageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage/deg-bhapka': {
      id: '/heritage/deg-bhapka'
      path: '/heritage/deg-bhapka'
      fullPath: '/heritage/deg-bhapka'
      preLoaderRoute: typeof HeritageDegBhapkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage/ingredients': {
      id: '/heritage/ingredients'
      path: '/heritage/ingredients'
      fullPath: '/heritage/ingredients'
      preLoaderRoute: typeof HeritageIngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage/story': {
      id: '/heritage/story'
      path: '/heritage/story'
      fullPath: '/heritage/story'
      preLoaderRoute: typeof HeritageStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/returns': {
      id: '/policies/returns'
      path: '/policies/returns'
      fullPath: '/policies/returns'
      preLoaderRoute: typeof PoliciesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/shipping': {
      id: '/policies/shipping'
      path: '/policies/shipping'
      fullPath: '/policies/shipping'
      preLoaderRoute: typeof PoliciesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/terms': {
      id: '/policies/terms'
      path: '/policies/terms'
      fullPath: '/policies/terms'
      preLoaderRoute: typeof PoliciesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collection/': {
      id: '/collections/$collection/'
      path: '/collections/$collection'
      fullPath: '/collections/$collection/'
      preLoaderRoute: typeof CollectionsCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$collection/': {
      id: '/shop/$collection/'
      path: '/shop/$collection'
      fullPath: '/shop/$collection/'
      preLoaderRoute: typeof ShopCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$collection/$slug': {
      id: '/shop/$collection/$slug'
      path: '/shop/$collection/$slug'
      fullPath: '/shop/$collection/$slug'
      preLoaderRoute: typeof ShopCollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogsRoute: CatalogsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HeritageDegBhapkaRoute: HeritageDegBhapkaRoute,
  HeritageIngredientsRoute: HeritageIngredientsRoute,
  HeritageStoryRoute: HeritageStoryRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesReturnsRoute: PoliciesReturnsRoute,
  PoliciesShippingRoute: PoliciesShippingRoute,
  PoliciesTermsRoute: PoliciesTermsRoute,
  HeritageIndexRoute: HeritageIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionSlugRoute: ShopCollectionSlugRoute,
  CollectionsCollectionIndexRoute: CollectionsCollectionIndexRoute,
  ShopCollectionIndexRoute: ShopCollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
